### ISSUE TITLE
Update q parameter inside of get_most_starred_python_repos

### ISSUE THREAD

**Issue by Lukasaurus11** [RecandChat/Github-Reccomendation-System#20]
Make it so that when we request repos  based on stars, we get multiple languages, instead of just python

**Comment by maudhelen** [comment]
should it be based on a user input? (i.e. we will give the user a menu "What languages are you interested in?")
or in the beginning just feed it a list and make a full dataset?

**Comment by Lukasaurus11** [comment]
I think since its to get the general information across multiple repositories we should at least fetch for the most popular programming languages

**Comment by gabrieldeolaguibel** [comment]
@maudhelen I disagree. I think our Reco engine should not be asking users for input. The input we get about coding languages should be extracted from the profile info

**Comment by Lukasaurus11** [comment]
#21
