### ISSUE TITLE
Add more relevant data to the dataset

### ISSUE THREAD

**Issue by felixggj** [RecandChat/Github-Reccomendation-System#22]
- There is too few data gathered from each repository
- We should find more datapoints from which to "feed" our pipeline, at the moment we only have repos by language type, and ordered by number of stars. There are not many insights we can extract from this.

**Some recommendations:**
- Example dataset with millions of GitHub repositories: https://www.kaggle.com/datasets/github/github-repos/data

**Comment by Lukasaurus11** [comment]
Take a look into the wikis, and tell us which fields you would like added, I think that adding a field like a commit signature or commit author is useless, but we can definitely improve the amount of data we store

**Comment by maudhelen** [comment]
Yes, adding on to what Luca said - what data would we find useful (and not restricted to the GitHub API)?

**Initial thoughts**:
- Could we maybe get repos/projects by combining popular courses on Coursera etc and finding their repos?
- Data about who follows who on GitHub

**Comment by felixggj** [comment]
When possible, I would like the following added:

* open_issues_count / open_issues (don't know the difference between the two, but I want the number of open issues) : This useful for recommending projects to users who want to contribute to open source projects.
* has_downloads : similar to star gazers count, but can help when doind EDA and visualisations
* topics : I'm aware that not all projects include them, but I will handle it, I just need as much data.
* forks : useful for evaluating how popular a project is

At the moment we need data, and the next step is to clean the data, which should be done after we analysed what we have, not before.

* It also be great to have a dataset with data from users -> I can help with this if needed

**Comment by Lukasaurus11** [comment]
> * It would also be great to have a dataset with data from users -> I can help with this if needed

What we can do for this is get the most starred repos list, and keep a set of the users that have contributed to them so that we don't have any sort of duplicates, and then call the function to get the repos for each of the users, which we combine with the starred repos data to then be saved. A problem that I can see from this though is that it will bias the model to only recommend projects from this users, but I think we were mostly already doing that

**Comment by maudhelen** [comment]
> When possible, I would like the following added:
> 
> * open_issues_count / open_issues (don't know the difference between the two, but I want the number of open issues) : This is useful for recommending projects to users who want to contribute to open source projects.
> * has_downloads : similar to star gazers count, but can help when doind EDA and visualisations
> * topics : I'm aware that not all projects include them, but I will handle it, I just need as much data.
> * forks : useful for evaluating how popular a project is
> 
> At the moment we need data, and the next step is to clean the data, which should be done after we analysed what we have, not before.
> 
> * It would also be great to have a dataset with data from users -> I can help with this if needed

i'll get to this tonight

**Comment by maudhelen** [comment]
@gabrieldeolaguibel is adding all the features/column possible and we rather exclude them after EDA. Once he is done you can close this issue

**Comment by gabrieldeolaguibel** [comment]
Done. It should not contain all possible features. It obviou
![Screenshot 2024-01-31 at 8 32 04 PM](https://github.com/RecandChat/Github-Reccomendation-System/assets/99414447/78e7eacc-d5b1-4910-a369-92b835437584)
sly excluding the millions links and stuff
